// src/pages/Players.vue
<script setup>
import { computed, ref, onMounted } from 'vue'
import teams from '../data/teams.json'
import PlayerCard from '../components/PlayerCard.vue'
import { getStats, ZERO_STATS } from '../utils/playerStats'
import { MIN_GP, REBOUND_MIN_GP } from '../utils/leaders'
import './Players.css'

const SORTS = {
  best5pts: { label: 'Points', short: 'PTS·5', desc: 'total points across each player’s 5 best games' },
  rpg: { label: 'Rebounds', short: 'RPG', desc: 'rebounds per game', minGp: REBOUND_MIN_GP },
  apg: { label: 'Assists', short: 'APG', desc: 'assists per game' },
  spg: { label: 'Steals', short: 'SPG', desc: 'steals per game' },
  bpg: { label: 'Blocks', short: 'BPG', desc: 'blocks per game' },
  tpm: { label: '3-Pointers Made', short: '3PM', desc: 'three-pointers made (season total)' },
}

const players = ref([])
const playerStats = ref({})
const query = ref('')
const teamFilter = ref('all')
const sortKey = ref('best5pts')

onMounted(async () => {
  const [playersRes, statsRes] = await Promise.all([fetch('/api/players'), fetch('/api/player-stats')])
  players.value = await playersRes.json()
  playerStats.value = await statsRes.json()
})

const sort = computed(() => SORTS[sortKey.value])
const minGp = computed(() => sort.value.minGp ?? MIN_GP)

const filtered = computed(() => {
  const q = query.value.trim().toLowerCase()
  const bySort = (a, b) => {
    const sa = getStats(playerStats.value, a.id)
    const sb = getStats(playerStats.value, b.id)
    return sb[sortKey.value] - sa[sortKey.value] || sb.ppg - sa.ppg
  }
  const matches = players.value
    .filter((p) => (q ? p.name.toLowerCase().includes(q) : true))
    .filter((p) => (teamFilter.value === 'all' ? true : p.team === teamFilter.value))

  return {
    qualified: matches.filter((p) => getStats(playerStats.value, p.id).gp >= minGp.value).sort(bySort),
    unqualified: matches.filter((p) => getStats(playerStats.value, p.id).gp < minGp.value).sort(bySort),
  }
})

const total = computed(() => filtered.value.qualified.length + filtered.value.unqualified.length)
</script>

<template>
  <div class="container">
    <span class="eyebrow">Rosters</span>
    <h1 class="section-title" style="font-size: 28px; margin-top: 8px">Players</h1>
    <p class="section-sub">
      {{ players.length }} players across 12 teams. Leaders ranked by {{ sort.desc }} &middot; min. {{ minGp }} games played.
    </p>

    <div class="players-filters">
      <input type="text" placeholder="Search player name..." v-model="query" />
      <select v-model="teamFilter">
        <option value="all">All Teams</option>
        <option v-for="t in teams" :key="t.id" :value="t.id">{{ t.name }}</option>
      </select>
      <select v-model="sortKey">
        <option v-for="(s, key) in SORTS" :key="key" :value="key">Sort: {{ s.label }}</option>
      </select>
    </div>

    <div v-if="total === 0" class="empty-state card">No players match your filters.</div>
    <template v-else>
      <div v-if="filtered.qualified.length > 0" class="grid players-grid">
        <PlayerCard
          v-for="p in filtered.qualified"
          :key="p.id"
          :player="p"
          :stats="getStats(playerStats, p.id)"
          :statKey="sortKey"
          :statLabel="sort.short"
        />
      </div>

      <template v-if="filtered.unqualified.length > 0">
        <div class="players-section-label">Not yet qualified &middot; under {{ minGp }} games</div>
        <div class="grid players-grid players-grid-dim">
          <PlayerCard
            v-for="p in filtered.unqualified"
            :key="p.id"
            :player="p"
            :stats="getStats(playerStats, p.id)"
            :statKey="sortKey"
            :statLabel="sort.short"
          />
        </div>
      </template>
    </template>
  </div>
</template>

// src/pages/Players.jsx
import { useMemo, useState } from 'react'
import players from '../data/players.json'
import teams from '../data/teams.json'
import PlayerCard from '../components/PlayerCard'
import { getPlayerStats } from '../utils/playerStats'
import { MIN_GP, REBOUND_MIN_GP } from '../utils/leaders'
import './Players.css'

const SORTS = {
  best5pts: { label: 'Points', short: 'PTS·5', desc: 'total points across each player’s 5 best games' },
  rpg: { label: 'Rebounds', short: 'RPG', desc: 'rebounds per game', minGp: REBOUND_MIN_GP },
  apg: { label: 'Assists', short: 'APG', desc: 'assists per game' },
  spg: { label: 'Steals', short: 'SPG', desc: 'steals per game' },
  bpg: { label: 'Blocks', short: 'BPG', desc: 'blocks per game' },
  tpm: { label: '3-Pointers Made', short: '3PM', desc: 'three-pointers made (season total)' },
}

export default function Players() {
  const [query, setQuery] = useState('')
  const [teamFilter, setTeamFilter] = useState('all')
  const [sortKey, setSortKey] = useState('best5pts')

  const minGp = SORTS[sortKey].minGp ?? MIN_GP

  const { qualified, unqualified } = useMemo(() => {
    const q = query.trim().toLowerCase()
    const bySort = (a, b) => {
      const sa = getPlayerStats(a.id)
      const sb = getPlayerStats(b.id)
      return sb[sortKey] - sa[sortKey] || sb.ppg - sa.ppg
    }
    const matches = players
      .filter((p) => (q ? p.name.toLowerCase().includes(q) : true))
      .filter((p) => (teamFilter === 'all' ? true : p.team === teamFilter))

    return {
      qualified: matches.filter((p) => getPlayerStats(p.id).gp >= minGp).sort(bySort),
      unqualified: matches.filter((p) => getPlayerStats(p.id).gp < minGp).sort(bySort),
    }
  }, [query, teamFilter, sortKey, minGp])

  const sort = SORTS[sortKey]
  const total = qualified.length + unqualified.length

  return (
    <div className="container">
      <span className="eyebrow">Rosters</span>
      <h1 className="section-title" style={{ fontSize: 28, marginTop: 8 }}>Players</h1>
      <p className="section-sub">
        {players.length} players across 12 teams. Leaders ranked by {sort.desc} &middot; min. {minGp} games played.
      </p>

      <div className="players-filters">
        <input
          type="text"
          placeholder="Search player name..."
          value={query}
          onChange={(e) => setQuery(e.target.value)}
        />
        <select value={teamFilter} onChange={(e) => setTeamFilter(e.target.value)}>
          <option value="all">All Teams</option>
          {teams.map((t) => (
            <option key={t.id} value={t.id}>{t.name}</option>
          ))}
        </select>
        <select value={sortKey} onChange={(e) => setSortKey(e.target.value)}>
          {Object.entries(SORTS).map(([key, s]) => (
            <option key={key} value={key}>Sort: {s.label}</option>
          ))}
        </select>
      </div>

      {total === 0 ? (
        <div className="empty-state card">No players match your filters.</div>
      ) : (
        <>
          {qualified.length > 0 && (
            <div className="grid players-grid">
              {qualified.map((p) => (
                <PlayerCard key={p.id} player={p} statKey={sortKey} statLabel={sort.short} />
              ))}
            </div>
          )}

          {unqualified.length > 0 && (
            <>
              <div className="players-section-label">Not yet qualified &middot; under {minGp} games</div>
              <div className="grid players-grid players-grid-dim">
                {unqualified.map((p) => (
                  <PlayerCard key={p.id} player={p} statKey={sortKey} statLabel={sort.short} />
                ))}
              </div>
            </>
          )}
        </>
      )}
    </div>
  )
}
