// src/pages/Schedule.jsx
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import schedule from '../data/schedule.json'
import teams from '../data/teams.json'
import TeamBadge from '../components/TeamBadge'
import { hasBoxscore } from '../utils/boxscores'
import { formatDate, formatTime } from '../utils/date'
import './Schedule.css'

const teamById = Object.fromEntries(teams.map((t) => [t.id, t]))

export default function Schedule() {
  const [teamFilter, setTeamFilter] = useState('all')
  const [statusFilter, setStatusFilter] = useState('all')

  const filtered = useMemo(() => {
    return schedule
      .filter((g) => teamFilter === 'all' || g.home === teamFilter || g.away === teamFilter)
      .filter((g) => statusFilter === 'all' || g.status === statusFilter)
      .sort((a, b) => a.date.localeCompare(b.date) || a.time.localeCompare(b.time))
  }, [teamFilter, statusFilter])

  const grouped = useMemo(() => {
    const map = new Map()
    filtered.forEach((g) => {
      if (!map.has(g.date)) map.set(g.date, [])
      map.get(g.date).push(g)
    })
    return [...map.entries()]
  }, [filtered])

  return (
    <div className="container">
      <span className="eyebrow">Season 4 Amlans Cup</span>
      <h1 className="section-title" style={{ fontSize: 28, marginTop: 8 }}>Schedule</h1>
      <p className="section-sub">Every matchup on the CGYBallers calendar.</p>

      <div className="schedule-filters">
        <select value={teamFilter} onChange={(e) => setTeamFilter(e.target.value)}>
          <option value="all">All Teams</option>
          {teams.map((t) => (
            <option key={t.id} value={t.id}>{t.name}</option>
          ))}
        </select>
        <select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}>
          <option value="all">All Games</option>
          <option value="scheduled">Upcoming</option>
          <option value="final">Final</option>
          <option value="cancelled">Cancelled</option>
        </select>
      </div>

      {grouped.length === 0 && (
        <div className="empty-state card">No games match these filters.</div>
      )}

      <div className="schedule-list">
        {grouped.map(([date, games]) => (
          <div key={date} className="schedule-day">
            <div className="schedule-date">{formatDate(date, { weekday: 'long', month: 'short', day: 'numeric' })}</div>
            {games.map((g) => (
              <div
                key={g.id}
                data-status={g.status}
                className={`card schedule-row ${g.status === 'cancelled' ? 'schedule-row-cancelled' : ''}`}
              >
                <div className="schedule-time">{formatTime(g.time)}</div>
                <div className="schedule-team">
                  <TeamBadge team={teamById[g.home]} size={32} />
                  <Link to={`/teams/${g.home}`}>{g.homeName}</Link>
                  <span className={`schedule-team-score ${g.status === 'final' && g.homeScore > g.awayScore ? 'win' : ''}`}>
                    {g.status === 'final' ? g.homeScore : g.status === 'scheduled' ? formatTime(g.time) : ''}
                  </span>
                </div>
                <div className="schedule-result">
                  {g.status === 'final' ? (
                    hasBoxscore(g.id) ? (
                      <Link to={`/games/${g.id}`} className="schedule-score schedule-score-link" title="View box score">
                        <b className={g.homeScore > g.awayScore ? 'win' : ''}>{g.homeScore}</b>
                        {' – '}
                        <b className={g.awayScore > g.homeScore ? 'win' : ''}>{g.awayScore}</b>
                      </Link>
                    ) : (
                      <span className="schedule-score">
                        <b className={g.homeScore > g.awayScore ? 'win' : ''}>{g.homeScore}</b>
                        {' – '}
                        <b className={g.awayScore > g.homeScore ? 'win' : ''}>{g.awayScore}</b>
                      </span>
                    )
                  ) : g.status === 'cancelled' ? (
                    <span className="schedule-vs">–</span>
                  ) : (
                    <span className="schedule-vs">@</span>
                  )}
                </div>
                <div className="schedule-team schedule-team-right">
                  <TeamBadge team={teamById[g.away]} size={32} />
                  <Link to={`/teams/${g.away}`}>{g.awayName}</Link>
                  <span className={`schedule-team-score ${g.status === 'final' && g.awayScore > g.homeScore ? 'win' : ''}`}>
                    {g.status === 'final' ? g.awayScore : ''}
                  </span>
                </div>
                <div className="schedule-footer">
                  <div className="schedule-venue">{g.venue}</div>
                  <span className={`badge schedule-status ${g.status === 'final' ? 'status-final' : ''} ${g.status === 'cancelled' ? 'status-cancelled' : ''}`}>
                    {g.status === 'final' ? 'Final' : g.status === 'cancelled' ? 'Cancelled' : 'Upcoming'}
                  </span>
                </div>
              </div>
            ))}
          </div>
        ))}
      </div>
    </div>
  )
}

// src/pages/Schedule.vue
<script setup>
import { computed, ref, onMounted } from 'vue'
import teams from '../data/teams.json'
import TeamBadge from '../components/TeamBadge.vue'
import { formatDate, formatTime } from '../utils/date'
import './Schedule.css'

const teamById = Object.fromEntries(teams.map((t) => [t.id, t]))

const schedule = ref([])
const teamFilter = ref('all')
const statusFilter = ref('all')

onMounted(async () => {
  const res = await fetch('/api/games')
  schedule.value = await res.json()
})

const filtered = computed(() => {
  return schedule.value
    .filter((g) => teamFilter.value === 'all' || g.home === teamFilter.value || g.away === teamFilter.value)
    .filter((g) => statusFilter.value === 'all' || g.status === statusFilter.value)
    .sort((a, b) => a.date.localeCompare(b.date) || a.time.localeCompare(b.time))
})

const grouped = computed(() => {
  const map = new Map()
  filtered.value.forEach((g) => {
    if (!map.has(g.date)) map.set(g.date, [])
    map.get(g.date).push(g)
  })
  return [...map.entries()]
})
</script>

<template>
  <div class="container">
    <span class="eyebrow">Season 4 Amlans Cup</span>
    <h1 class="section-title" style="font-size: 28px; margin-top: 8px">Schedule</h1>
    <p class="section-sub">Every matchup on the CGYBallers calendar.</p>

    <div class="schedule-filters">
      <select v-model="teamFilter">
        <option value="all">All Teams</option>
        <option v-for="t in teams" :key="t.id" :value="t.id">{{ t.name }}</option>
      </select>
      <select v-model="statusFilter">
        <option value="all">All Games</option>
        <option value="scheduled">Upcoming</option>
        <option value="final">Final</option>
        <option value="forfeit">Forfeit</option>
        <option value="cancelled">Cancelled</option>
      </select>
    </div>

    <div v-if="grouped.length === 0" class="empty-state card">No games match these filters.</div>

    <div class="schedule-list">
      <div v-for="[date, games] in grouped" :key="date" class="schedule-day">
        <div class="schedule-date">{{ formatDate(date, { weekday: 'long', month: 'short', day: 'numeric' }) }}</div>
        <div
          v-for="g in games"
          :key="g.id"
          :data-status="g.status"
          :class="['card schedule-row', g.status === 'cancelled' ? 'schedule-row-cancelled' : '']"
        >
          <div class="schedule-time">{{ formatTime(g.time) }}</div>
          <div class="schedule-team">
            <TeamBadge :team="teamById[g.home]" :size="32" />
            <router-link :to="`/teams/${g.home}`">{{ g.homeName }}</router-link>
            <span
              :class="[
                'schedule-team-score',
                (g.status === 'final' && g.homeScore > g.awayScore) || (g.status === 'forfeit' && g.winner === g.home) ? 'win' : '',
              ]"
            >
              {{
                g.status === 'final'
                  ? g.homeScore
                  : g.status === 'forfeit' && g.winner === g.home
                  ? 'FF'
                  : g.status === 'scheduled'
                  ? formatTime(g.time)
                  : ''
              }}
            </span>
          </div>
          <div class="schedule-result">
            <router-link
              v-if="g.status === 'final' && g.hasBoxscore"
              :to="`/games/${g.id}`"
              class="schedule-score schedule-score-link"
              title="View box score"
            >
              <b :class="g.homeScore > g.awayScore ? 'win' : ''">{{ g.homeScore }}</b>
              {{ ' – ' }}
              <b :class="g.awayScore > g.homeScore ? 'win' : ''">{{ g.awayScore }}</b>
            </router-link>
            <span v-else-if="g.status === 'final'" class="schedule-score">
              <b :class="g.homeScore > g.awayScore ? 'win' : ''">{{ g.homeScore }}</b>
              {{ ' – ' }}
              <b :class="g.awayScore > g.homeScore ? 'win' : ''">{{ g.awayScore }}</b>
            </span>
            <span v-else-if="g.status === 'forfeit'" class="schedule-vs">FF</span>
            <span v-else-if="g.status === 'cancelled'" class="schedule-vs">–</span>
            <span v-else class="schedule-vs">@</span>
          </div>
          <div class="schedule-team schedule-team-right">
            <TeamBadge :team="teamById[g.away]" :size="32" />
            <router-link :to="`/teams/${g.away}`">{{ g.awayName }}</router-link>
            <span
              :class="[
                'schedule-team-score',
                (g.status === 'final' && g.awayScore > g.homeScore) || (g.status === 'forfeit' && g.winner === g.away) ? 'win' : '',
              ]"
            >
              {{ g.status === 'final' ? g.awayScore : g.status === 'forfeit' && g.winner === g.away ? 'FF' : '' }}
            </span>
          </div>
          <div class="schedule-footer">
            <div class="schedule-venue">{{ g.venue }}</div>
            <span
              :class="[
                'badge schedule-status',
                g.status === 'final' ? 'status-final' : '',
                g.status === 'forfeit' ? 'status-forfeit' : '',
                g.status === 'cancelled' ? 'status-cancelled' : '',
              ]"
            >
              {{ g.status === 'final' ? 'Final' : g.status === 'forfeit' ? 'Forfeit' : g.status === 'cancelled' ? 'Cancelled' : 'Upcoming' }}
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
