// src/pages/Standings.jsx
import { Link } from 'react-router-dom'
import standings from '../utils/standings'
import teams from '../data/teams.json'
import TeamBadge from '../components/TeamBadge'

export default function Standings() {
  return (
    <div className="container">
      <span className="eyebrow">Season 4 Amlans Cup</span>
      <h1 className="section-title" style={{ fontSize: 28, marginTop: 8 }}>Standings</h1>
      <p className="section-sub">League table.</p>

      <div className="card table-scroll">
        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>Team</th>
              <th>GP</th>
              <th>W</th>
              <th>L</th>
            </tr>
          </thead>
          <tbody>
            {standings.map((row) => (
              <tr key={row.team}>
                <td>{row.rank}</td>
                <td>
                  <Link
                    to={`/teams/${row.team}`}
                    style={{ display: 'flex', alignItems: 'center', gap: 8, fontWeight: 700 }}
                  >
                    <TeamBadge team={teams.find((t) => t.id === row.team)} size={24} />
                    {row.name}
                  </Link>
                </td>
                <td>{row.gp}</td>
                <td>{row.wins}</td>
                <td>{row.losses}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

// src/pages/Standings.vue
<script setup>
import { ref, onMounted } from 'vue'
import teams from '../data/teams.json'
import TeamBadge from '../components/TeamBadge.vue'

const standings = ref([])

onMounted(async () => {
  const res = await fetch('/api/standings')
  standings.value = await res.json()
})
</script>

<template>
  <div class="container">
    <span class="eyebrow">Season 4 Amlans Cup</span>
    <h1 class="section-title" style="font-size: 28px; margin-top: 8px">Standings</h1>
    <p class="section-sub">League table.</p>

    <div class="card table-scroll">
      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Team</th>
            <th>GP</th>
            <th>W</th>
            <th>L</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="row in standings" :key="row.team">
            <td>{{ row.rank }}</td>
            <td>
              <router-link
                :to="`/teams/${row.team}`"
                style="display: flex; align-items: center; gap: 8px; font-weight: 700"
              >
                <TeamBadge :team="teams.find((t) => t.id === row.team)" :size="24" />
                {{ row.name }}
              </router-link>
            </td>
            <td>{{ row.gp }}</td>
            <td>{{ row.wins }}</td>
            <td>{{ row.losses }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>
