// src/pages/Teams.jsx
import { Link } from 'react-router-dom'
import teams from '../data/teams.json'
import standings from '../data/standings.json'
import TeamBadge from '../components/TeamBadge'
import './Teams.css'

const standingsByTeam = Object.fromEntries(standings.map((s) => [s.team, s]))

export default function Teams() {
  return (
    <div className="container">
      <span className="eyebrow">League</span>
      <h1 className="section-title" style={{ fontSize: 28, marginTop: 8 }}>Teams</h1>
      <p className="section-sub">All 12 teams competing this season.</p>

      <div className="grid teams-grid">
        {teams.map((t) => {
          const record = standingsByTeam[t.id]
          return (
            <Link key={t.id} to={`/teams/${t.id}`} className="card team-card">
              <TeamBadge team={t} size={48} />
              <div>
                <div className="team-card-name">{t.name}</div>
                <div className="team-card-meta">
                  {record ? `${record.wins}-${record.losses}` : '0-0'} &middot; {t.playerIds.length} players
                </div>
              </div>
            </Link>
          )
        })}
      </div>
    </div>
  )
}

// src/pages/Teams.vue
<script setup>
import { ref, computed, onMounted } from 'vue'
import TeamBadge from '../components/TeamBadge.vue'
import './Teams.css'

const teams = ref([])
const standings = ref([])
const standingsByTeam = computed(() => Object.fromEntries(standings.value.map((s) => [s.team, s])))

onMounted(async () => {
  const [teamsRes, standingsRes] = await Promise.all([fetch('/api/teams'), fetch('/api/standings')])
  teams.value = await teamsRes.json()
  standings.value = await standingsRes.json()
})
</script>

<template>
  <div class="container">
    <span class="eyebrow">League</span>
    <h1 class="section-title" style="font-size: 28px; margin-top: 8px">Teams</h1>
    <p class="section-sub">All 12 teams competing this season.</p>

    <div class="grid teams-grid">
      <router-link
        v-for="t in teams"
        :key="t.id"
        :to="`/teams/${t.id}`"
        class="card team-card"
      >
        <TeamBadge :team="t" :size="48" />
        <div>
          <div class="team-card-name">{{ t.name }}</div>
          <div class="team-card-meta">
            {{ standingsByTeam[t.id] ? `${standingsByTeam[t.id].wins}-${standingsByTeam[t.id].losses}` : '0-0' }}
            &middot; {{ t.playerIds.length }} players
          </div>
        </div>
      </router-link>
    </div>
  </div>
</template>
